# Generated by Django 4.0.4 on 2022-04-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_update_at_alter_post_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='head_imag',
            field=models.ImageField(blank=True, upload_to='blog/images/%Y/%m/%d/'),
        ),
    ]
